### ISSUE TITLE
malicious code

### ISSUE THREAD

**Issue by user9102d** [Uber-Eins/FileCentipede-Automatic-Activation#3]
How much do we want to bet this goes unanswered..\

[https://www.virustotal.com/gui/file/165e987bbe22b34ca0dca67b3544d1a9189c3fa91573022d82202e6e6c43569a/detection](url)

![filecenti](https://github.com/Uber-Eins/FileCentipede-Automatic-Activation/assets/65014400/ee510873-fa8f-4a64-b4d2-85b1b082d047)

**Comment by Uber-Eins** [comment]
Dude, this Python source code is accessible to beginners, why don't you check it out?
If you're worried about the risks of pre-compiled files, you can also compile it yourself.
